export const modules = [
  {
    id: 1,
    title: "Networking Foundation",
    summary: "Core concepts of how networks work, OSI model, and network components.",
    duration: "2 Weeks",
    level: "Beginner",
    tools: ["Cisco Packet Tracer"],
    miniProject: "Build a simple LAN topology",
    weeks: [
      {
        week: 1,
        sessions: [
          {
            session: 1,
            title: "Introduction to Networking",
            topics: ["What is networking?", "Types of networks (LAN, WAN, MAN)", "Client-server concept", "Network components overview"],
            lab: "Build first network topology in Cisco Packet Tracer",
            commands: ["show version", "show interfaces"],
            troubleshooting: "Identify why two PCs cannot communicate",
            homework: "Document 5 real-world network scenarios",
            outcome: "Understand networking fundamentals and identify network components",
          },
          {
            session: 2,
            title: "OSI & TCP/IP Model",
            topics: ["OSI 7-layer model deep dive", "TCP/IP 4-layer model", "Layer responsibilities", "Protocol mapping"],
            lab: "Analyze packet flow using Packet Tracer simulation mode",
            commands: ["ping", "traceroute", "show arp"],
            troubleshooting: "Trace where communication fails in a broken topology",
            homework: "Map a real application (HTTP) across all OSI layers",
            outcome: "Explain how data traverses the OSI/TCP-IP stack",
          },
        ],
      },
      {
        week: 2,
        sessions: [
          {
            session: 3,
            title: "Network Devices & Cables",
            topics: ["Hub vs Switch vs Router", "Cable types (UTP, fiber, coax)", "Physical layer concepts", "Network topologies"],
            lab: "Connect devices using correct cable types in Packet Tracer",
            commands: ["show interfaces status", "show cdp neighbors"],
            troubleshooting: "Identify incorrect cable type causing link failure",
            homework: "Design a network diagram for a small office",
            outcome: "Select appropriate devices and cabling for network scenarios",
          },
          {
            session: 4,
            title: "Introduction to CLI & IOS",
            topics: ["Cisco IOS navigation", "Exec modes", "Basic device configuration", "Show commands"],
            lab: "Configure hostnames, passwords, banners on routers and switches",
            commands: ["enable", "configure terminal", "hostname", "enable secret", "service password-encryption"],
            troubleshooting: "Recover from locked-out device using password recovery",
            homework: "Build and configure a 3-device topology with full documentation",
            outcome: "Navigate Cisco IOS and perform basic device hardening",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "IP Addressing & Subnetting",
    summary: "Master IPv4/IPv6 addressing, subnetting math, and CIDR notation.",
    duration: "2 Weeks",
    level: "Beginner",
    tools: ["Cisco Packet Tracer", "Subnet Calculator"],
    miniProject: "Design IP addressing scheme for a multi-department office",
    weeks: [
      {
        week: 3,
        sessions: [
          {
            session: 5,
            title: "IPv4 Addressing",
            topics: ["Binary math for networking", "IPv4 structure", "Address classes", "Public vs Private addresses", "Special addresses"],
            lab: "Assign IP addresses and verify connectivity",
            commands: ["ip address", "show ip interface brief", "show ip route"],
            troubleshooting: "Fix misconfigured IP addresses causing connectivity issues",
            homework: "Convert 20 IP addresses to binary and back",
            outcome: "Assign and validate IPv4 addresses across a network",
          },
          {
            session: 6,
            title: "Subnetting Fundamentals",
            topics: ["Subnet mask mechanics", "CIDR notation", "Network/broadcast/host calculation", "Subnetting methodology"],
            lab: "Subnet a /24 into 8 equal subnets and configure them",
            commands: ["show ip interface", "ping", "show run | include ip address"],
            troubleshooting: "Identify wrong subnet mask causing network isolation",
            homework: "Complete 30 subnetting practice problems",
            outcome: "Perform subnetting calculations without a calculator",
          },
        ],
      },
      {
        week: 4,
        sessions: [
          {
            session: 7,
            title: "VLSM & Supernetting",
            topics: ["Variable Length Subnet Masking", "Efficient address allocation", "Route summarization basics", "Supernetting/CIDR aggregation"],
            lab: "Design VLSM scheme for headquarters with 5 departments",
            commands: ["ip route", "show ip route", "show ip interface brief"],
            troubleshooting: "Resolve overlapping subnet issues in a VLSM design",
            homework: "Design VLSM for a campus with 12 buildings",
            outcome: "Design efficient IP addressing using VLSM",
          },
          {
            session: 8,
            title: "IPv6 Addressing",
            topics: ["IPv6 structure and notation", "Address types (unicast, multicast, anycast)", "EUI-64", "IPv6 transition mechanisms"],
            lab: "Configure IPv6 on routers and verify neighbor discovery",
            commands: ["ipv6 address", "show ipv6 interface brief", "show ipv6 neighbors", "ping ipv6"],
            troubleshooting: "Fix IPv6 connectivity issues in dual-stack environment",
            homework: "Plan an IPv6 migration strategy for a small company",
            outcome: "Configure and troubleshoot basic IPv6 networks",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Switching Technologies",
    summary: "VLANs, STP, EtherChannel, and enterprise switching architecture.",
    duration: "3 Weeks",
    level: "Intermediate",
    tools: ["Cisco Packet Tracer", "GNS3"],
    miniProject: "Multi-VLAN office network with redundant uplinks",
    weeks: [
      {
        week: 5,
        sessions: [
          {
            session: 9,
            title: "VLANs & Trunking",
            topics: ["VLAN concepts and benefits", "Access vs Trunk ports", "802.1Q tagging", "Native VLAN"],
            lab: "Configure VLANs across multiple switches with trunk links",
            commands: ["vlan", "switchport mode access", "switchport access vlan", "switchport mode trunk", "show vlan brief", "show interfaces trunk"],
            troubleshooting: "Fix VLAN mismatch causing inter-switch communication failure",
            homework: "Design VLAN structure for a 200-user enterprise",
            outcome: "Configure and verify VLAN segmentation across switches",
          },
          {
            session: 10,
            title: "Inter-VLAN Routing",
            topics: ["Router-on-a-stick", "Layer 3 switching", "SVI configuration", "Subinterface configuration"],
            lab: "Enable inter-VLAN routing using both methods",
            commands: ["interface fastethernet 0/0.10", "encapsulation dot1q", "ip routing", "interface vlan"],
            troubleshooting: "Diagnose why VLAN 20 hosts cannot reach VLAN 30",
            homework: "Compare RoaS vs L3 switch performance tradeoffs",
            outcome: "Implement inter-VLAN routing using multiple techniques",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    title: "Routing & Enterprise Routing",
    summary: "Static routing, OSPF, EIGRP, BGP fundamentals, and redistribution.",
    duration: "3 Weeks",
    level: "Intermediate",
    tools: ["GNS3", "Cisco Packet Tracer"],
    miniProject: "Multi-site OSPF network with redundant paths",
    weeks: [],
  },
  {
    id: 5,
    title: "Network Services",
    summary: "DHCP, DNS, NAT/PAT, NTP, and syslog configuration.",
    duration: "2 Weeks",
    level: "Intermediate",
    tools: ["GNS3", "Cisco Packet Tracer"],
    miniProject: "Full enterprise service stack configuration",
    weeks: [],
  },
  {
    id: 6,
    title: "Wireless Networking",
    summary: "WiFi standards, WLC configuration, enterprise wireless design.",
    duration: "2 Weeks",
    level: "Intermediate",
    tools: ["Cisco Packet Tracer", "Omada SDN"],
    miniProject: "Enterprise wireless network design",
    weeks: [],
  },
  {
    id: 7,
    title: "Network Security & Firewall",
    summary: "ACLs, port security, AAA, Zone-Based Firewall, and basic IDS/IPS.",
    duration: "2 Weeks",
    level: "Advanced",
    tools: ["GNS3", "EVE-NG"],
    miniProject: "Secure branch office with firewall policies",
    weeks: [],
  },
  {
    id: 8,
    title: "QoS & Optimization",
    summary: "Traffic shaping, classification, queuing, and WAN optimization.",
    duration: "1 Week",
    level: "Advanced",
    tools: ["GNS3"],
    miniProject: "QoS policy for voice/video priority",
    weeks: [],
  },
  {
    id: 9,
    title: "Advanced Networking Concepts",
    summary: "MPLS, SD-WAN overview, network virtualization, and overlay networks.",
    duration: "1 Week",
    level: "Advanced",
    tools: ["EVE-NG"],
    miniProject: "MPLS VPN simulation",
    weeks: [],
  },
  {
    id: 10,
    title: "Network Automation",
    summary: "Python for networking, Ansible, REST APIs, and NetConf/YANG.",
    duration: "2 Weeks",
    level: "Advanced",
    tools: ["Python", "Ansible", "GNS3"],
    miniProject: "Automate device configuration with Ansible playbook",
    weeks: [],
  },
  {
    id: 11,
    title: "Final Capstone",
    summary: "Design, implement, and document a full enterprise network from scratch.",
    duration: "2 Weeks",
    level: "Capstone",
    tools: ["GNS3", "EVE-NG", "Packet Tracer"],
    miniProject: "Complete enterprise network with VLAN, routing, security, wireless, QoS",
    weeks: [],
  },
];

export const caseStudies = [
  {
    week: "Week 3–4",
    title: "Office Internet Down",
    problem: "All employees suddenly lost internet access on a Monday morning. Last change was a firewall update Friday.",
    requirement: "Diagnose and restore connectivity within 30 minutes using systematic troubleshooting.",
    deliverables: ["Root cause analysis report", "Step-by-step troubleshooting log", "Configuration fix with validation"],
  },
  {
    week: "Week 5–6",
    title: "Branch Office Connectivity Failure",
    problem: "The Surabaya branch office cannot reach the Jakarta HQ server farm. VPN tunnel shows connected.",
    requirement: "Identify routing or ACL issue and restore full branch connectivity.",
    deliverables: ["Network diagram with annotated issue", "Routing table analysis", "Fixed configuration backup"],
  },
  {
    week: "Week 7–8",
    title: "VLAN Segmentation Issue",
    problem: "Finance VLAN can access HR database — a critical security breach scenario.",
    requirement: "Audit and fix VLAN segmentation, apply proper ACLs, and verify isolation.",
    deliverables: ["Security audit report", "ACL ruleset documentation", "Before/after verification"],
  },
  {
    week: "Week 9–10",
    title: "Slow Enterprise WiFi",
    problem: "Meeting rooms experience degraded WiFi. Users report Zoom calls dropping every 10 minutes.",
    requirement: "Analyze RF environment, reconfigure WLC, and implement QoS for voice/video.",
    deliverables: ["RF site survey report", "WLC configuration changes", "QoS policy document"],
  },
];

export const faqs = [
  {
    q: "Is this beginner friendly?",
    a: "Yes. The curriculum is meticulously designed to start from absolute fundamentals (OSI Model, IP Addresses) and progressively scales up to advanced enterprise configurations without overwhelming you.",
  },
  {
    q: "Do I need networking experience?",
    a: "No prior networking experience is required. Basic IT literacy is helpful, but we build your networking knowledge from the ground up, assuming zero prior configuration experience.",
  },
  {
    q: "Will we use Cisco?",
    a: "Yes, Cisco is our primary vendor for teaching routing and switching concepts because of its industry dominance. We use Cisco Packet Tracer and GNS3 extensively. The concepts learned, however, are vendor-neutral and apply to Juniper, Mikrotik, and HP.",
  },
  {
    q: "Will this help with university networking courses?",
    a: "Absolutely. Many university courses focus heavily on academic theory. This bootcamp bridges that gap by providing the hands-on configuration and real-world troubleshooting experience that universities often miss.",
  },
  {
    q: "How practical is the learning?",
    a: "Extremely practical. Every single session includes a hands-on lab. You won't just read about OSPF; you will build an OSPF topology, intentionally break it, and then troubleshoot the failure.",
  },
  {
    q: "Will we only learn theory?",
    a: "Theory is only the first step. Our pedagogical flow is: Learn the Theory → Build the Topology → Troubleshoot Failures → Think Like an Engineer. Theory exists only to serve practical implementation.",
  },
];
